name: deriva
description: A Dart API for the DERIVA platform.
# version: 0.0.1
# homepage: https://github.com/robes/deriva-dart
# author: schuler <robes@users.noreply.github.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
