name: deriva
version: 0.2.0
description: Dart API for the DERIVA platform.
homepage: https://deriva.isi.edu

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  http: ^0.13.0
  http_retry: ^0.2.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
